package com.learning.springboot.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data  //This one will create all the getter and setter methords
@NoArgsConstructor //creates no args constructor
@AllArgsConstructor //Creates all args constructor
public class Student {
    //The below two lines are used to set roll number as primary key
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)  //Make ID as autoGenerated
    private long rollNo;
    private String name;


}
